name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify .NET SDK Version
        run: dotnet --info  #  Check if .NET 8 is installed

      - name: Fix Permissions for `bin/` and `obj/`
        run: |
          sudo rm -rf bin obj  
          mkdir -p bin obj      
          sudo chmod -R 777 bin obj  
          sudo chown -R $(whoami):$(whoami) bin obj  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Publish solution
        run: dotnet publish --no-restore --configuration Release -o out
