name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/SimpleDotNetService.sln  # ✅ Fix path

      - name: Build solution
        run: dotnet build src/SimpleDotNetService.sln --no-restore --configuration Release  # ✅ Fix path

      - name: Publish solution
        run: dotnet publish src/SimpleDotNetService.sln --no-restore --configuration Release -o out  # ✅ Fix path

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: out
